server {
    listen 8444 ssl;
    server_name portfolioks.duckdns.org;

    ssl_certificate /etc/letsencrypt/live/portfolioks.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/portfolioks.duckdns.org/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    root /usr/share/nginx/html;
    index index.html;

    location ~* \.mp4$ {
        root /usr/share/nginx/html;
        try_files $uri $uri/ =404;
        add_header Accept-Ranges bytes;
        expires max;
        add_header Cache-Control "public, no-transform";
    }

    location / {
        try_files $uri $uri.html $uri/ /index.html;
    }
}
